name: Github script

on:
  workflow_dispatch:

jobs:
  github-script:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Github script
        uses: actions/github-script@v6
        with:
          script: |
            function handle() {
              throw new Error("Try custom exception")
            }

            try {
              console.log('Try')
              handle()
            } catch(e) {
              console.log('Catch')
              handle()
            }
