name: Github script

on:
  workflow_dispatch:

jobs:
  github-script:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Create new issue
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.TOKEN }}
          script: |
            async function createGitHubIssue() {
              const issueTitle = 'Testing'
              const issueBody = '### Title test';
            
              const duplicate_issue_request =
                await github.rest.search.issuesAndPullRequests({
                  q: `repo:${{ github.repository }} is:issue is:open in:title ${issueTitle}`,
                });
              const issue_exists = duplicate_issue_request.data.total_count > 0;
              if (issue_exists) {
                throw new Error(`There's already an issue for \"${issueTitle}\"`);
              } else {
                github.rest.issues.create({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  title: issueTitle,
                  body: issueBody,
                });
              }
            }

            try {
              await createGitHubIssue()
            } catch (error) {
              const { 
                response: {
                  data: {
                    message
                  }
                } 
              } = error

              if (message === 'You have exceeded a secondary rate limit. Please wait a few minutes before you try again.') {
                await createGitHubIssue()
              } else {
                console.log(error)
              }
            }