name: trigger-release

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:

  schedule:
    - cron: "0 6 * * 0"

jobs:
  trigger-build-and-release:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: Get current version
        id: version-app
        uses: ./.github/actions/app-version
        with:
          GRADLE_FILE: gradle.properties

      - name: Trigger app release build
        env:
          GIT_BRANCH: ${{ github.ref_name }}
          VERSION_NAME: ${{ steps.version-app.outputs.version_name }}
        run: |
          set -eou pipefail

          current_branch=${GIT_BRANCH:-$(git branch --show-current)}
          branch_name="release/$VERSION_NAME-RC"
          remote_branch=$(git ls-remote --heads origin "$branch_name")
          
          if [[ ! -z "$remote_branch" ]]; then
            echo "The $branch_name remote branch  already exist"
            exit 0
          fi
          
          echo "git checkout -b $branch_name"
          echo "git push origin $branch_name --tags"
          echo "git checkout $current_branch"
          echo "Successfully pushed to remote."
